name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Run workflow when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name group3staticweb12345 --source . --destination '$web' --overwrite --auth-mode login
